nelmio_api_doc:
    documentation:
        info:
            title: Cometa Club
            description: API for Afilliate program
            version: 1.0.0 beta
        security:
            - Bearer: []
        paths:
            /api/v1/login:
                post:
                    description: api login
                    tags:
                        - User management
                    parameters:
                        - in: query
                          name: username
                          required: true
                          schema:
                            type: string
                        - in: query
                          name: password
                          required: true
                          schema:
                            type: string
                    responses:
                        200:
                            description: ok
                            content: 
                                application/json: 
                                    schema: 
                                        type: object
                                        properties:
                                            email: { type: string, example: 'string'}
                                            password: { type: string, example: 'string'}
        components:
            securitySchemes:
                    Bearer:
                        type: http
                        scheme: bearer
                        bearerFormat: JWT   
    areas: # to filter documented areas
        path_patterns:
            - ^/api/v1
